### ISSUE TITLE
Does the Forward-Eluer method only forward pass the first frame point cloud?

### ISSUE THREAD

**Issue by Agito555** [kavisha725/MBNSF#2]
I really appreciate your article and the well-organized code. After reading your implementation of forward Euler, I have a question: it seems that your method only projects the point cloud of the first frame to the target frame using the predicted scene flow. Please correct me if I'm wrong.

**Comment by kavisha725** [comment]
Hi, Thanks for your interest. 
Yes, the code release only provides implementation of forward Euler for the [first frame](https://github.com/kavisha725/MBNSF/blob/192e483b8050500711cbf3d89a5424f23f29d7c6/trajectory_estimation/nsfp_fe.py#L203). This is for the purpose of evaluating the accuracy of trajectory prediction. If you are more interested in point cloud densification, for example, you can easily extend the code to project all frames to the last frame.
